# Generated by Django 4.2.5 on 2023-09-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_contact_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='femail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_name',
            new_name='phone',
        ),
    ]
